### ISSUE TITLE
Customizing Effects for Golden Apples [Bug]

### ISSUE THREAD

**Issue by GrimCrusader** [gvlfm78/BukkitOldCombatMechanics#172]
No matter what I try, it won't let me add new effects, they always come out giving an error in console saying that the effects are "null". My config for them is below. Thank you
 ```
gapple-effects:
    regeneration:
      duration: 100
      amplifier: 1
    absorption:
      duration: 2400
      amplifier: 0
  # Potion effects enchanted golden apples should apply
  napple-effects:
    regeneration:
      duration: 600
      amplifier: 4
    damage_resistance:
      duration: 6000
      amplifier: 0
    fire_resistance:
      duration: 6000
      amplifier: 0
    absorption:
      duration: 2400
      amplifier: 0
    slowness:
      duration: 600
      amplifier: 2
    strength:
      duration: 600
      amplifier: 0
```
