### ISSUE TITLE
Napple gives 8 absorption instead of 2

### ISSUE THREAD

**Issue by xion87** [gvlfm78/BukkitOldCombatMechanics#262]
## Info

- Server version:  Paper 1.13.2
- OldCombatMechanics version: 1.7.0
- OldCombatMechanics config file: 
```yaml
  napple-effects:
    regeneration:
      duration: 600
      amplifier: 4
    damage_resistance:
      duration: 6000
      amplifier: 0
    fire_resistance:
      duration: 6000
      amplifier: 0
    absorption:
      duration: 2400
      amplifier: 0
```

## Problem Description
I noticed using enchanted apple (notch apple) it give 8 assorbtion hearts instead 2 (as 1.8 old effect) and keep to use assobition 4
