### ISSUE TITLE
Health always at 19/20

### ISSUE THREAD

**Issue by hasanas83V2001** [gvlfm78/BukkitOldCombatMechanics#42]
So, when at "full health" there's always a half heart missing, even when eating a golden apple or when respawning, the health will always be at 19/20. I don't know what causes this, I didn't find anything in the config about it, running spigot 1.11.2

**Comment by gvlfm78** [comment]
What version of OCM are you running?

**Comment by hasanas83V2001** [comment]
The latest (1.1.2)

**Comment by gvlfm78** [comment]
Could you try with the [latest test build](https://jenkins-gvl.rhcloud.com/job/OldCombatMechanics/lastSuccessfulBuild/) and see if the error is still present?
Also, do you have old player regen enabled in the config?

**Comment by hasanas83V2001** [comment]
I tried going on the latest test build, it did not make a difference, here are my old player regen settings:
old-player-regen:
  enabled: true
  worlds: []
  amount: 1
  exhaustion: 3

**Comment by gvlfm78** [comment]
Do you not have a frequency setting there?

```
old-player-regen:
  # This is to make players' regeneration act mostly like it did in pre-1.9
  # It's hard to make it behave exactly like before, but in general this makes it work like in pre-1.9
  enabled: true
  worlds: []
  # How often, in seconds, a player should regenerate health
  frequency: 3
  # How many half-hearts the player should heal by, every seconds specified above
  amount: 1
  # How much exhaustion healing should give to the player. In 1.8: 3 In 1.9: 4 in 1.11: 6
  # If, after adding this, Minecraft finds the value is above 4, it subtracts 4
  # and either reduces saturation or, if saturation is 0, reduces food level by 1 (1/2 a stick)
  exhaustion: 3
```
