### ISSUE TITLE
Fishing rod gets stuck in a player if you are in a non-pvp area.

### ISSUE THREAD

**Issue by mibby** [gvlfm78/BukkitOldCombatMechanics#54]
OCM dev 72

With old fishing knockback enabled, if you right click someone with a fishing rod, the rod gets stuck in the player. (Not sure if this typically happens in vanilla behavior where the rods get put inside the player entity.) If you are in a non-pvp zone, your rod is permanently stuck inside the player when you try to right click to pull it out, as damage is cancelled. Only when swapping items in your hand will the rod go away.

```
old-fishing-knockback:
  # This is to make the knockback of players when they get hit by a fishing bobber the same as it was in pre-1.9
  # Credit to HyKurtis for the original code, optimised by Rayzr522
  enabled: true
  worlds: []
  # This makes OCM check if other plugins are stopping the rod damage and follow their choice
  # Set to false to always have rod damage
  checkCancelled: false
  # This is the damage done by the fishing rod attack
  damage: 0.2
```
